In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import torch
import numpy as np

In [ ]:
x=torch.empty(5,4)
print(x)

tensor([[1.4633e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [ ]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.zeros(2)

tensor([0., 0.])

In [ ]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [ ]:
torch.rand(5,6)

tensor([[0.7499, 0.6904, 0.6469, 0.4214, 0.1211, 0.5280],
        [0.1538, 0.3743, 0.3164, 0.3931, 0.9635, 0.6781],
        [0.2513, 0.8711, 0.7620, 0.7510, 0.3964, 0.9761],
        [0.9534, 0.6494, 0.1409, 0.2259, 0.3185, 0.8145],
        [0.8211, 0.2272, 0.8891, 0.1095, 0.4648, 0.4633]])

In [ ]:
num_list=[13,4]
r=np.array([1,56,7])
num_list=torch.tensor(num_list)
torch.tensor(r)

tensor([ 1, 56,  7])

In [ ]:
num_list.size()

torch.Size([2])

In [ ]:
x.size()[1]

4

x.size()[1] 이 4가 나오는 이유를 모르겠어서 검색해 보았다. 배열 1개의 크기가 4인 것인가?
https://wikidocs.net/52460 
이 사이트에 텐서와 텐서의 조작에 대해 잘 나와있었다.


In [ ]:
x.size()

torch.Size([5, 4])

In [ ]:
x.size()[0]

5

In [6]:
#난수 배열 생성
x=torch.rand(2,2)
y=torch.rand(2,2)
x+y
#더하기 여러 방식
torch.add(x,y)
y.add(x)
y.add_(x)

tensor([[0.9500, 1.2104],
        [1.7494, 0.3860]])

In [11]:
x=torch.rand(8,8)
print(x.size())

torch.Size([8, 8])


In [13]:
a=x.view(64) #열벡터
print(a.size())

torch.Size([64])


In [15]:
b=x.view(16,4) #16x4 벡터
print(b.size())

torch.Size([16, 4])


In [17]:
x=torch.ones(2,2,requires_grad=True)
y=x+1
z=2*y**2
r=z.mean()
print("Result:",r)

Result: tensor(8., grad_fn=<MeanBackward0>)
